// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/amanhigh/go-fun/common/util"
	"github.com/amanhigh/go-fun/models/common"
	"github.com/amanhigh/go-fun/models/fun"
	mock "github.com/stretchr/testify/mock"
)

// NewEnrollmentDaoInterface creates a new instance of EnrollmentDaoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnrollmentDaoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnrollmentDaoInterface {
	mock := &EnrollmentDaoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EnrollmentDaoInterface is an autogenerated mock type for the EnrollmentDaoInterface type
type EnrollmentDaoInterface struct {
	mock.Mock
}

type EnrollmentDaoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *EnrollmentDaoInterface) EXPECT() *EnrollmentDaoInterface_Expecter {
	return &EnrollmentDaoInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) Create(c context.Context, entity any, omit ...string) common.HttpError {
	var tmpRet mock.Arguments
	if len(omit) > 0 {
		tmpRet = _mock.Called(c, entity, omit)
	} else {
		tmpRet = _mock.Called(c, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...string) common.HttpError); ok {
		r0 = returnFunc(c, entity, omit...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EnrollmentDaoInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c context.Context
//   - entity any
//   - omit ...string
func (_e *EnrollmentDaoInterface_Expecter) Create(c interface{}, entity interface{}, omit ...interface{}) *EnrollmentDaoInterface_Create_Call {
	return &EnrollmentDaoInterface_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{c, entity}, omit...)...)}
}

func (_c *EnrollmentDaoInterface_Create_Call) Run(run func(c context.Context, entity any, omit ...string)) *EnrollmentDaoInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_Create_Call) Return(err common.HttpError) *EnrollmentDaoInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnrollmentDaoInterface_Create_Call) RunAndReturn(run func(c context.Context, entity any, omit ...string) common.HttpError) *EnrollmentDaoInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) DeleteById(c context.Context, id any, entity any) common.HttpError {
	ret := _mock.Called(c, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any) common.HttpError); ok {
		r0 = returnFunc(c, id, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type EnrollmentDaoInterface_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - c context.Context
//   - id any
//   - entity any
func (_e *EnrollmentDaoInterface_Expecter) DeleteById(c interface{}, id interface{}, entity interface{}) *EnrollmentDaoInterface_DeleteById_Call {
	return &EnrollmentDaoInterface_DeleteById_Call{Call: _e.mock.On("DeleteById", c, id, entity)}
}

func (_c *EnrollmentDaoInterface_DeleteById_Call) Run(run func(c context.Context, id any, entity any)) *EnrollmentDaoInterface_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_DeleteById_Call) Return(err common.HttpError) *EnrollmentDaoInterface_DeleteById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnrollmentDaoInterface_DeleteById_Call) RunAndReturn(run func(c context.Context, id any, entity any) common.HttpError) *EnrollmentDaoInterface_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) FindById(c context.Context, id any, entity any) common.HttpError {
	ret := _mock.Called(c, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any) common.HttpError); ok {
		r0 = returnFunc(c, id, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type EnrollmentDaoInterface_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - c context.Context
//   - id any
//   - entity any
func (_e *EnrollmentDaoInterface_Expecter) FindById(c interface{}, id interface{}, entity interface{}) *EnrollmentDaoInterface_FindById_Call {
	return &EnrollmentDaoInterface_FindById_Call{Call: _e.mock.On("FindById", c, id, entity)}
}

func (_c *EnrollmentDaoInterface_FindById_Call) Run(run func(c context.Context, id any, entity any)) *EnrollmentDaoInterface_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_FindById_Call) Return(err common.HttpError) *EnrollmentDaoInterface_FindById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnrollmentDaoInterface_FindById_Call) RunAndReturn(run func(c context.Context, id any, entity any) common.HttpError) *EnrollmentDaoInterface_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPersonID provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) FindByPersonID(ctx context.Context, personID string, enrollment *fun.Enrollment) common.HttpError {
	ret := _mock.Called(ctx, personID, enrollment)

	if len(ret) == 0 {
		panic("no return value specified for FindByPersonID")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *fun.Enrollment) common.HttpError); ok {
		r0 = returnFunc(ctx, personID, enrollment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_FindByPersonID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPersonID'
type EnrollmentDaoInterface_FindByPersonID_Call struct {
	*mock.Call
}

// FindByPersonID is a helper method to define mock.On call
//   - ctx context.Context
//   - personID string
//   - enrollment *fun.Enrollment
func (_e *EnrollmentDaoInterface_Expecter) FindByPersonID(ctx interface{}, personID interface{}, enrollment interface{}) *EnrollmentDaoInterface_FindByPersonID_Call {
	return &EnrollmentDaoInterface_FindByPersonID_Call{Call: _e.mock.On("FindByPersonID", ctx, personID, enrollment)}
}

func (_c *EnrollmentDaoInterface_FindByPersonID_Call) Run(run func(ctx context.Context, personID string, enrollment *fun.Enrollment)) *EnrollmentDaoInterface_FindByPersonID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *fun.Enrollment
		if args[2] != nil {
			arg2 = args[2].(*fun.Enrollment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_FindByPersonID_Call) Return(httpError common.HttpError) *EnrollmentDaoInterface_FindByPersonID_Call {
	_c.Call.Return(httpError)
	return _c
}

func (_c *EnrollmentDaoInterface_FindByPersonID_Call) RunAndReturn(run func(ctx context.Context, personID string, enrollment *fun.Enrollment) common.HttpError) *EnrollmentDaoInterface_FindByPersonID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPaginated provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) FindPaginated(c context.Context, pageParams common.Pagination, result any) (int64, common.HttpError) {
	ret := _mock.Called(c, pageParams, result)

	if len(ret) == 0 {
		panic("no return value specified for FindPaginated")
	}

	var r0 int64
	var r1 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Pagination, any) (int64, common.HttpError)); ok {
		return returnFunc(c, pageParams, result)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Pagination, any) int64); ok {
		r0 = returnFunc(c, pageParams, result)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Pagination, any) common.HttpError); ok {
		r1 = returnFunc(c, pageParams, result)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}
	return r0, r1
}

// EnrollmentDaoInterface_FindPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPaginated'
type EnrollmentDaoInterface_FindPaginated_Call struct {
	*mock.Call
}

// FindPaginated is a helper method to define mock.On call
//   - c context.Context
//   - pageParams common.Pagination
//   - result any
func (_e *EnrollmentDaoInterface_Expecter) FindPaginated(c interface{}, pageParams interface{}, result interface{}) *EnrollmentDaoInterface_FindPaginated_Call {
	return &EnrollmentDaoInterface_FindPaginated_Call{Call: _e.mock.On("FindPaginated", c, pageParams, result)}
}

func (_c *EnrollmentDaoInterface_FindPaginated_Call) Run(run func(c context.Context, pageParams common.Pagination, result any)) *EnrollmentDaoInterface_FindPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Pagination
		if args[1] != nil {
			arg1 = args[1].(common.Pagination)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_FindPaginated_Call) Return(count int64, err common.HttpError) *EnrollmentDaoInterface_FindPaginated_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *EnrollmentDaoInterface_FindPaginated_Call) RunAndReturn(run func(c context.Context, pageParams common.Pagination, result any) (int64, common.HttpError)) *EnrollmentDaoInterface_FindPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// GetByExternalId provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) GetByExternalId(c context.Context, externalId string, entity any) common.HttpError {
	ret := _mock.Called(c, externalId, entity)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalId")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) common.HttpError); ok {
		r0 = returnFunc(c, externalId, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_GetByExternalId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByExternalId'
type EnrollmentDaoInterface_GetByExternalId_Call struct {
	*mock.Call
}

// GetByExternalId is a helper method to define mock.On call
//   - c context.Context
//   - externalId string
//   - entity any
func (_e *EnrollmentDaoInterface_Expecter) GetByExternalId(c interface{}, externalId interface{}, entity interface{}) *EnrollmentDaoInterface_GetByExternalId_Call {
	return &EnrollmentDaoInterface_GetByExternalId_Call{Call: _e.mock.On("GetByExternalId", c, externalId, entity)}
}

func (_c *EnrollmentDaoInterface_GetByExternalId_Call) Run(run func(c context.Context, externalId string, entity any)) *EnrollmentDaoInterface_GetByExternalId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_GetByExternalId_Call) Return(err common.HttpError) *EnrollmentDaoInterface_GetByExternalId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnrollmentDaoInterface_GetByExternalId_Call) RunAndReturn(run func(c context.Context, externalId string, entity any) common.HttpError) *EnrollmentDaoInterface_GetByExternalId_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) GetCount(c context.Context, entity any) (int64, common.HttpError) {
	ret := _mock.Called(c, entity)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int64
	var r1 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) (int64, common.HttpError)); ok {
		return returnFunc(c, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) int64); ok {
		r0 = returnFunc(c, entity)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any) common.HttpError); ok {
		r1 = returnFunc(c, entity)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}
	return r0, r1
}

// EnrollmentDaoInterface_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type EnrollmentDaoInterface_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - c context.Context
//   - entity any
func (_e *EnrollmentDaoInterface_Expecter) GetCount(c interface{}, entity interface{}) *EnrollmentDaoInterface_GetCount_Call {
	return &EnrollmentDaoInterface_GetCount_Call{Call: _e.mock.On("GetCount", c, entity)}
}

func (_c *EnrollmentDaoInterface_GetCount_Call) Run(run func(c context.Context, entity any)) *EnrollmentDaoInterface_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_GetCount_Call) Return(count int64, err common.HttpError) *EnrollmentDaoInterface_GetCount_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *EnrollmentDaoInterface_GetCount_Call) RunAndReturn(run func(c context.Context, entity any) (int64, common.HttpError)) *EnrollmentDaoInterface_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) Update(c context.Context, entity any, omit ...string) common.HttpError {
	var tmpRet mock.Arguments
	if len(omit) > 0 {
		tmpRet = _mock.Called(c, entity, omit)
	} else {
		tmpRet = _mock.Called(c, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...string) common.HttpError); ok {
		r0 = returnFunc(c, entity, omit...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EnrollmentDaoInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - c context.Context
//   - entity any
//   - omit ...string
func (_e *EnrollmentDaoInterface_Expecter) Update(c interface{}, entity interface{}, omit ...interface{}) *EnrollmentDaoInterface_Update_Call {
	return &EnrollmentDaoInterface_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{c, entity}, omit...)...)}
}

func (_c *EnrollmentDaoInterface_Update_Call) Run(run func(c context.Context, entity any, omit ...string)) *EnrollmentDaoInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_Update_Call) Return(err common.HttpError) *EnrollmentDaoInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnrollmentDaoInterface_Update_Call) RunAndReturn(run func(c context.Context, entity any, omit ...string) common.HttpError) *EnrollmentDaoInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UseOrCreateTx provides a mock function for the type EnrollmentDaoInterface
func (_mock *EnrollmentDaoInterface) UseOrCreateTx(c context.Context, run util.DbRun, readOnly ...bool) common.HttpError {
	var tmpRet mock.Arguments
	if len(readOnly) > 0 {
		tmpRet = _mock.Called(c, run, readOnly)
	} else {
		tmpRet = _mock.Called(c, run)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UseOrCreateTx")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.DbRun, ...bool) common.HttpError); ok {
		r0 = returnFunc(c, run, readOnly...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentDaoInterface_UseOrCreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseOrCreateTx'
type EnrollmentDaoInterface_UseOrCreateTx_Call struct {
	*mock.Call
}

// UseOrCreateTx is a helper method to define mock.On call
//   - c context.Context
//   - run util.DbRun
//   - readOnly ...bool
func (_e *EnrollmentDaoInterface_Expecter) UseOrCreateTx(c interface{}, run interface{}, readOnly ...interface{}) *EnrollmentDaoInterface_UseOrCreateTx_Call {
	return &EnrollmentDaoInterface_UseOrCreateTx_Call{Call: _e.mock.On("UseOrCreateTx",
		append([]interface{}{c, run}, readOnly...)...)}
}

func (_c *EnrollmentDaoInterface_UseOrCreateTx_Call) Run(run func(c context.Context, run util.DbRun, readOnly ...bool)) *EnrollmentDaoInterface_UseOrCreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.DbRun
		if args[1] != nil {
			arg1 = args[1].(util.DbRun)
		}
		var arg2 []bool
		var variadicArgs []bool
		if len(args) > 2 {
			variadicArgs = args[2].([]bool)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *EnrollmentDaoInterface_UseOrCreateTx_Call) Return(err common.HttpError) *EnrollmentDaoInterface_UseOrCreateTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EnrollmentDaoInterface_UseOrCreateTx_Call) RunAndReturn(run func(c context.Context, run util.DbRun, readOnly ...bool) common.HttpError) *EnrollmentDaoInterface_UseOrCreateTx_Call {
	_c.Call.Return(run)
	return _c
}
