# Theme: Default
direction: right
production: @lib/prod
...@lib/styles

production: {
  user: @lib/user

  frontend: @lib/service
  backend: @lib/service-vm
  db: @lib/dbset

  user -> frontend.dns

  backend.cluster -- db.master: DB Access
  frontend.cluster -> backend.dns: API Access

  # Styling Section
  user.class: med # Multiple [a;b]
  (user -> frontend.dns)[0].class: Test-dotted
  (frontend.cluster -> backend.dns)[0].class: smed
  (backend.cluster -- db.master)[0].class: smed
}
