direction: right
production: @lib/cloud

production: {
  user: @lib/user

  frontend: @lib/service
  backend: @lib/service
  db: @lib/dbset

  user -> frontend.dns: {
    style.stroke: crimson
    style.stroke-width: 5
    style.stroke-dash: 3
  }

  backend.cluster -- db.master
  frontend.cluster -> backend.dns
}
