apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    accessible_namespaces:
      - "**"
  auth:
    strategy: anonymous
