version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - cyclop
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - ginkgolinter
    - gocritic
    - gocyclo
    - gosec
    - govet
    - lll
    - mnd
    - nilerr
    - noctx
    - nolintlint
    - revive
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - whitespace
  settings:
    cyclop:
      max-complexity: 10
      package-average: 8
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 40
      statements: 20
    gocritic:
      enabled-checks:
        - paramTypeCombine
        - appendCombine
        - sloppyReassign
    gocyclo:
      min-complexity: 10
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 200
    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "2"
      ignored-functions:
        - make
    revive:
      rules:
        - name: dot-imports
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: argument-limit
          arguments:
            - 6
        - name: function-result-limit
          arguments:
            - 3
    wrapcheck:
      ignore-sigs:
        - ^fmt\.Errorf$
        - ^time\.Parse$
        - ^errors\.New$
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: '^dot-imports:'
      - linters:
          - bodyclose
        path: common/clients/http_client.go
      - linters:
          - errcheck
          - govet
          - mnd
          - wrapcheck
        path: components/learn/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 15
  max-same-issues: 3
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
