# This is the best config for golangci-lint based on my experience and opinion.
# It is very strict, but not extremely strict.
# Feel free to adapt and change it for your needs.
# Source: https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

version: "2"
# https://golangci-lint.run/usage/linters/#funlen
linters:
  default: none
  enable:
    # TODO: #C Strengthen linters and fix issues.
    # High Priority - Code Correctness & Bugs
    - errcheck      # critical error checking
    - govet        # suspicious constructs
    - staticcheck  # advanced static analysis
    - gosec        # security checks
    # - wrapcheck    # error wrapping validation
    
    # Safety & Resources
    - bodyclose      # ensure http response closed
    - nilerr        # nil error returns
    - sqlclosecheck # ensure sql resources closed
    - noctx        # enforce context usage
    - mnd           # Magic numbers detector
    - unconvert    # type conversion
    
    # Code Style Essentials
    # - goimports     # import sorting + gofmt
    - revive        # general style (golint replacement)
    - gocritic      
    - unused        # unused code detection
    - nolintlint    # nolint linter

    # Consider enabling these linters later:
    - exhaustive     # enum switch statements
    - gosec         # security checks
    - errorlint     # error wrapping (Go 1.13+)
    - testifylint   # testify best practices
    - whitespace    # ws formatting
    - ginkgolinter  # ginkgo best practices
    # - dupl           # duplicate code detection
    # - ireturn        # interface return

    # Complexity
    - gocyclo      # Cyclomatic complexity
    - cyclop       # Package complexity and maintainability
    - funlen       # Function length control
    - lll          # Line length control
    - interfacebloat # interface bloat
    
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment # too strict
    mnd:
        # Exclude some common acceptable numbers
        ignored-numbers: ["0","1","2"]
        ignored-functions: ["make"]

    funlen:
      lines: 40      # max function length
      statements: 20  # max statements per function
      
    lll:
      line-length: 200  # max line length
      
    # Complexity Control
    gocyclo:
      min-complexity: 10  # cyclomatic complexity limit
      
    cyclop:
      max-complexity: 10
      package-average: 8

    errcheck:
      check-type-assertions: true
    wrapcheck:
      ignorePackageGlobs:
        - "github.com/amanhigh/go-fun/components/..." # Ignore errors originating from our own repo components
      ignoreSigs:
        - ^fmt\.Errorf$  # Already formatted errors
        - ^time\.Parse$  # Simple parsing errors
        - ^errors\.New$  # Basic error creation
    # https://go-critic.com/overview
    gocritic:
      enabled-checks:
        - paramTypeCombine    # Combines same-type params
        - appendCombine     # Merge redundant `append` calls
        - sloppyReassign    # Detect redundant variable reassignments

    # https://revive.run/docs#default-configuration
    revive:
      # enable-all-rules: true
      rules:
        # - name: var-naming
        - name: dot-imports
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: argument-limit
          arguments: [6]      # Max parameters
        - name: function-result-limit
          arguments: [3]      # Max return values
  exclusions:
    generated: lax
    # TODO: Renable this.
    warn-unused: false
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: '^dot-imports:'
      - linters:
          - bodyclose
        path: common/clients/http_client.go
      - linters:
          - errcheck
          - govet
          - mnd
          - wrapcheck
        path: components/learn/
    paths:
issues:
  max-issues-per-linter: 15
  max-same-issues: 3
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
output:
  sort-order:
    - linter
    - severity