# Make sure to check the documentation at https://goreleaser.com
# goreleaser check
# goreleaser build --snapshot --rm-dist
# goreleaser release --snapshot --skip-publish --rm-dist
#
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
#      - windows
    id: fun
    binary: fun-app
    main: ./apps/components/fun-app/fun-app.go

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
