# Make sure to check the documentation at https://goreleaser.com
# Variables available - https://goreleaser.com/customization/templates/
# goreleaser check
# goreleaser build --snapshot --rm-dist
# goreleaser release --snapshot --skip-publish --rm-dist
#
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
#      - windows
    goarch:
    - amd64
    id: fun
    binary: fun
    dir: ./apps/components/fun-app
    main: fun-app.go

dockers:
    - id: fun-app
      image_templates:
        - "amanfdk/fun-app"
        - "amanfdk/fun-app:{{ .Version }}"
      dockerfile: ./apps/components/fun-app/Dockerfile
      extra_files:
        - ./apps/components/fun-app/config.yml