root = "."
tmp_dir = "/tmp/ui-demo"

[build]
  cmd = "make -C ../../../../../ build-air"
  entrypoint = "/tmp/ui-demo/main"
  delay = 1000
  include_ext = ["go", "templ", "ts"]
  include_dir = [".", "../components", "../pages", ".."]
  exclude_regex = ["_test\\.go", "_templ\\.go"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
