definitions:
  db.Person:
    properties:
      age:
        type: integer
      gender:
        enum:
        - MALE
        - FEMALE
        type: string
      name:
        type: string
    required:
    - age
    - gender
    - name
    type: object
  server.PersonRequest:
    properties:
      age:
        type: integer
      gender:
        enum:
        - MALE
        - FEMALE
        type: string
      name:
        type: string
    required:
    - age
    - gender
    - name
    type: object
info:
  contact: {}
paths:
  /person:
    post:
      consumes:
      - application/json
      description: Create a new person with the provided data
      parameters:
      - description: Person Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.PersonRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.PersonRequest'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new person
      tags:
      - Person
  /person/{id}:
    delete:
      consumes:
      - application/json
      description: Delete persons by their ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: DELETED
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete persons by ID
      tags:
      - Person
    get:
      consumes:
      - application/json
      description: Get a person's details by their ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Person'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get a person by ID
      tags:
      - Person
  /person/all:
    get:
      consumes:
      - application/json
      description: Get all persons' details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Person'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all persons
      tags:
      - Person
swagger: "2.0"
