definitions:
  common.PaginatedResponse:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  fun.Student:
    properties:
      age:
        maximum: 150
        minimum: 1
        type: integer
      gender:
        enum:
        - MALE
        - FEMALE
        type: string
      id:
        type: string
      name:
        description: Validations - https://gin-gonic.com/docs/examples/binding-and-validation/
        maxLength: 25
        minLength: 1
        type: string
    required:
    - age
    - gender
    - name
    type: object
  fun.StudentAudit:
    properties:
      age:
        type: integer
      auditID:
        description: Audit Fields
        type: integer
      createdAt:
        type: string
      createdBy:
        description: 'TODO: Use Base Dao of Gorm for common Fields ?'
        type: string
      gender:
        type: string
      id:
        type: string
      name:
        type: string
      operation:
        type: string
    type: object
  fun.StudentList:
    properties:
      metadata:
        $ref: '#/definitions/common.PaginatedResponse'
      records:
        items:
          $ref: '#/definitions/fun.Student'
        type: array
    type: object
  fun.StudentRequest:
    properties:
      age:
        maximum: 150
        minimum: 1
        type: integer
      gender:
        enum:
        - MALE
        - FEMALE
        type: string
      name:
        description: Validations - https://gin-gonic.com/docs/examples/binding-and-validation/
        maxLength: 25
        minLength: 1
        type: string
    required:
    - age
    - gender
    - name
    type: object
info:
  contact: {}
paths:
  /student:
    get:
      consumes:
      - application/json
      description: List Student and Optionally Search
      parameters:
      - description: Filter students by name
        in: query
        name: name
        type: string
      - description: Filter students by gender
        in: query
        name: gender
        type: string
      - description: Filter students by age
        in: query
        name: age
        type: integer
      - description: Sort order
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      - description: Sort by
        enum:
        - name
        - gender
        - age
        in: query
        name: sort_by
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fun.StudentList'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List Student and Search
      tags:
      - Student
    post:
      consumes:
      - application/json
      description: Create a new student with the provided data
      parameters:
      - description: Student Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/fun.StudentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Id of created student
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new student
      tags:
      - Student
  /student/{id}:
    delete:
      consumes:
      - application/json
      description: Delete students by their ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: DELETED
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete students by ID
      tags:
      - Student
    get:
      consumes:
      - application/json
      description: Get a student's details by their ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fun.Student'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get a student by ID
      tags:
      - Student
    put:
      consumes:
      - application/json
      description: Update a student's details
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      - description: Student Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/fun.StudentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: UPDATED
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a student
      tags:
      - Student
  /student/{id}/audit:
    get:
      consumes:
      - application/json
      description: List Student Audit by ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/fun.StudentAudit'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List Student Audit
      tags:
      - Student
swagger: "2.0"
