classes: {
  base: {
    style: {
      border-radius: 4
      shadow: true
    }
  }

  stk-dotted: {
    style.stroke: crimson
    style.stroke-width: 5
    style.stroke-dash: 3
  }

  stk-invisible: {
    style.opacity: 0.0
  }

  smed: {
    style.stroke-width: 3
    style.font-size: 30
  }

  sred: {
    style.stroke-width: 3
    style.stroke: red
  }

  pass: {
    style.fill: limegreen
    style.stroke: green
  }

  error: {
    style.fill: crimson
    style.stroke: orange
  }

  mini: {
    width: 50
    height: 50
    style.font-size: 8
  }

  small: {
    width: 100
    height: 100
    style.font-size: 14
  }

  med: {
    width: 200
    height: 200
    style.font-size: 24
  }
  large: {
    width: 300
    height: 300
    style.font-size: 28
  }
  xlarge: {
    width: 400
    height: 400
    style.font-size: 32
  }

  person: {
    shape: person
    style.stroke-dash: 3
  }
}
