apiVersion: v2
name: fun-app
description: App build on Go to Have Fun and Learn

type: application

# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# TODO: Goreleaser helm release
# This is the version number of the application being deployed.
appVersion: "1.0.2"
