apiVersion: apps/v1
kind: Deployment
metadata:
  name: fun-app
spec:
  replicas: 1 #Cound of App Pods
  selector:
    matchLabels:
      app: fun-app
      version: v1
  template:
    metadata:
      labels:
        app: fun-app #Name of App
        version: v1 #Version of this Deployment
    spec:
      serviceAccountName: fun-app
      containers:
      - image: amanfdk/fun-app #Image to be used
        imagePullPolicy: IfNotPresent
        name: fun-app
        ports:
          - containerPort: 8080 # Port on Which App Runs
        readinessProbe:
          exec:
            command:
              - ls
          # httpGet: 
          #   port: 8080
          #   path: /metrics
          initialDelaySeconds: 3
          periodSeconds: 5
            
            
