apiVersion: apps/v1
kind: Deployment
metadata:
  name: fun-app
spec:
  replicas: 1 #Cound of App Pods
  selector:
    matchLabels:
      app: fun-app
      version: v1
  template:
    metadata:
      labels:
        app: fun-app #Name of App
        version: v1 #Version of this Deployment
    spec:
      serviceAccountName: fun-app
      containers:
      - image: amanfdk/fun-app #Image to be used
        imagePullPolicy: IfNotPresent
        # command: ["sh","-c","sleep 10000"]
        name: fun-app
        ports:
          - containerPort: 8080 # Port on Which App Runs
        env:
          - name: DB_URL
            value: "aman:aman@tcp(fun-mysql:3306)/compute?charset=utf8&parseTime=True&loc=Local"
        readinessProbe: #Probe to test if Pod is Up
          httpGet: 
            port: 8080
            path: /metrics
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe: #Probe to test that Pod is Healthy
          httpGet: 
            port: 8080
            path: /metrics
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
            
