# Default values for ..

service:
  #TODO: Expose in Minikube and Update Notes
  port: 9000
  dbUrl: "aman:aman@tcp(fun-app-mysql:3306)/compute?charset=utf8&parseTime=True&loc=Local"
  # requestTimeout: 2s
  # idle_connectionTimeout: 60s

rateLimit:
  redis: fun-app-redis-master:6379
  perMin: 300

replicaCount: 1

#CPU: kubectl -n fun-app autoscale deployment fun-app --name=fun-app-hpa --cpu-percent=50 --min=1 --max=4
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  cpuPercentage: 70
  memoryPercentage: 80
  scaleDownWindowSeconds: 60 #Time to scaledown post resource usage below limits

mysql:
  auth:
    rootPassword: root
    database: compute
    username: aman
    password: aman

redis:
  auth:
    enabled: false
    password: ""
  replica:
    replicaCount: 1
