# Default values for ..

service:
  port: 9000
  db_url: "aman:aman@tcp(fun-mysql:3306)/compute?charset=utf8&parseTime=True&loc=Local"

replicaCount: 1

# TODO: Apply Autoscale
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
