# Default values for ..

service:
  #TODO: Expose in Minikube and Update Notes
  port: 9000
  dbUrl: "aman:aman@tcp(fun-app-mysql:3306)/compute?charset=utf8&parseTime=True&loc=Local"
  # requestTimeout: 2s
  # idle_connectionTimeout: 60s

rateLimit:
  redis: fun-app-redis-master:6379
  perMin: 300

replicaCount: 1

# TODO: Apply Autoscale
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

mysql:
  auth:
    rootPassword: root
    database: compute
    username: aman
    password: aman

redis:
  auth:
    enabled: false
    password: ""
  replica:
    replicaCount: 1
