{
 "title": "FunApp",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Main metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GetAll: Student Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(fun_app_student_count[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "StudentCreate: TimeBuckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "fun_app_student_create_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "API-Status Access",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(gin_access_requests_total[5m])",
     "legendFormat": "{{url}}-{{code}}"
    }
   ]
  },
  {
   "title": "Go Routine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "go_goroutines{app=\"fun-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}