# FIXME: #B Add Response Wrapper
### Rest API - https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
### Rest Sample - https://github.com/cryptlex/rest-api-response-format
### Pagination - https://dev.to/pragativerma18/unlocking-the-power-of-api-pagination-best-practices-and-strategies-4b49
### Swagger Editor - https://editor-next.swagger.io/
### https://github.com/Huachao/vscode-restclient
### Person CRUD
### LIST

### Variables
@host=localhost
@port=8085

### List

GET http://{{host}}:{{port}}/v1/person?limit=10

### Create
POST http://{{host}}:{{port}}/v1/person
Content-Type: application/json

{
    "name": "Amanpreet Singh",
    "age": 31,
    "gender": "MALE"
}

### Get
GET http://{{host}}:{{port}}/v1/person/GCBOT

### Delete
DELETE http://{{host}}:{{port}}/v1/person/amanpreet

