# FIXME: Add Response Wrapper
### Rest API - https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
### Swagger Editor - https://editor.swagger.io/
### Person CRUD
### LIST
GET http://localhost:8085/v1/person

### Create
POST http://localhost:8085/v1/person
Content-Type: application/json

{
    "name": "Amanpreet Singh",
    "age": 31,
    "gender": "MALE"
}

### Get
GET http://localhost:8085/v1/person/GCBOT

### Delete
DELETE http://localhost:8085/v1/person/amanpreet
