### Rest API
# https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
# https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/
### Error Handling
# https://www.baeldung.com/rest-api-error-handling-best-practices
# https://www.rfc-editor.org/rfc/rfc7807
# https://stackoverflow.com/questions/12806386/is-there-any-standard-for-json-api-response-format
### Rest Sample
# https://github.com/cryptlex/rest-api-response-format
# https://github.com/omniti-labs/jsend
# https://docs.github.com/en/rest/teams/teams
#
### Pagination
# https://dev.to/pragativerma18/unlocking-the-power-of-api-pagination-best-practices-and-strategies-4b49
# https://developer.atlassian.com/server/confluence/pagination-in-the-rest-api/
# 
### Swagger Editor - https://editor-next.swagger.io/
### https://github.com/Huachao/vscode-restclient

### Variables
# Environment Variables in workspace settings.
@limit={{$randomInt 2 5}}

### List

GET http://{{host}}:{{port}}/{{version}}/person?limit={{limit}}&sort_by=name&order=asc

### Create
# @name createPerson
POST http://{{host}}:{{port}}/{{version}}/person
Content-Type: application/json

{
    "name": "Amanpreet Singh",
    "age": 31,
    "gender": "MALE"
}

### Get
@personId= {{createPerson.response.body.$.id}}
GET http://{{host}}:{{port}}/{{version}}/person/{{personId}}

### Delete
# @prompt userId
DELETE http://{{host}}:{{port}}/{{version}}/person/{{userId}}

### Play
POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "llama3",
  "prompt":"Generate Sample Golang Code"
}'