// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/amanhigh/go-fun/models/common"
	"github.com/amanhigh/go-fun/models/fun"
	mock "github.com/stretchr/testify/mock"
)

// NewEnrollmentPublisher creates a new instance of EnrollmentPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnrollmentPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnrollmentPublisher {
	mock := &EnrollmentPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EnrollmentPublisher is an autogenerated mock type for the EnrollmentPublisher type
type EnrollmentPublisher struct {
	mock.Mock
}

type EnrollmentPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *EnrollmentPublisher) EXPECT() *EnrollmentPublisher_Expecter {
	return &EnrollmentPublisher_Expecter{mock: &_m.Mock}
}

// Enroll provides a mock function for the type EnrollmentPublisher
func (_mock *EnrollmentPublisher) Enroll(ctx context.Context, enrollment fun.Enrollment) common.HttpError {
	ret := _mock.Called(ctx, enrollment)

	if len(ret) == 0 {
		panic("no return value specified for Enroll")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, fun.Enrollment) common.HttpError); ok {
		r0 = returnFunc(ctx, enrollment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentPublisher_Enroll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enroll'
type EnrollmentPublisher_Enroll_Call struct {
	*mock.Call
}

// Enroll is a helper method to define mock.On call
//   - ctx context.Context
//   - enrollment fun.Enrollment
func (_e *EnrollmentPublisher_Expecter) Enroll(ctx interface{}, enrollment interface{}) *EnrollmentPublisher_Enroll_Call {
	return &EnrollmentPublisher_Enroll_Call{Call: _e.mock.On("Enroll", ctx, enrollment)}
}

func (_c *EnrollmentPublisher_Enroll_Call) Run(run func(ctx context.Context, enrollment fun.Enrollment)) *EnrollmentPublisher_Enroll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fun.Enrollment
		if args[1] != nil {
			arg1 = args[1].(fun.Enrollment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EnrollmentPublisher_Enroll_Call) Return(httpError common.HttpError) *EnrollmentPublisher_Enroll_Call {
	_c.Call.Return(httpError)
	return _c
}

func (_c *EnrollmentPublisher_Enroll_Call) RunAndReturn(run func(ctx context.Context, enrollment fun.Enrollment) common.HttpError) *EnrollmentPublisher_Enroll_Call {
	_c.Call.Return(run)
	return _c
}

// EnrollmentCancelledEvt provides a mock function for the type EnrollmentPublisher
func (_mock *EnrollmentPublisher) EnrollmentCancelledEvt(ctx context.Context, enrollment fun.Enrollment, reason string) common.HttpError {
	ret := _mock.Called(ctx, enrollment, reason)

	if len(ret) == 0 {
		panic("no return value specified for EnrollmentCancelledEvt")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, fun.Enrollment, string) common.HttpError); ok {
		r0 = returnFunc(ctx, enrollment, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentPublisher_EnrollmentCancelledEvt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrollmentCancelledEvt'
type EnrollmentPublisher_EnrollmentCancelledEvt_Call struct {
	*mock.Call
}

// EnrollmentCancelledEvt is a helper method to define mock.On call
//   - ctx context.Context
//   - enrollment fun.Enrollment
//   - reason string
func (_e *EnrollmentPublisher_Expecter) EnrollmentCancelledEvt(ctx interface{}, enrollment interface{}, reason interface{}) *EnrollmentPublisher_EnrollmentCancelledEvt_Call {
	return &EnrollmentPublisher_EnrollmentCancelledEvt_Call{Call: _e.mock.On("EnrollmentCancelledEvt", ctx, enrollment, reason)}
}

func (_c *EnrollmentPublisher_EnrollmentCancelledEvt_Call) Run(run func(ctx context.Context, enrollment fun.Enrollment, reason string)) *EnrollmentPublisher_EnrollmentCancelledEvt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fun.Enrollment
		if args[1] != nil {
			arg1 = args[1].(fun.Enrollment)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EnrollmentPublisher_EnrollmentCancelledEvt_Call) Return(httpError common.HttpError) *EnrollmentPublisher_EnrollmentCancelledEvt_Call {
	_c.Call.Return(httpError)
	return _c
}

func (_c *EnrollmentPublisher_EnrollmentCancelledEvt_Call) RunAndReturn(run func(ctx context.Context, enrollment fun.Enrollment, reason string) common.HttpError) *EnrollmentPublisher_EnrollmentCancelledEvt_Call {
	_c.Call.Return(run)
	return _c
}

// EnrollmentConfirmedEvt provides a mock function for the type EnrollmentPublisher
func (_mock *EnrollmentPublisher) EnrollmentConfirmedEvt(ctx context.Context, enrollment fun.Enrollment) common.HttpError {
	ret := _mock.Called(ctx, enrollment)

	if len(ret) == 0 {
		panic("no return value specified for EnrollmentConfirmedEvt")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, fun.Enrollment) common.HttpError); ok {
		r0 = returnFunc(ctx, enrollment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// EnrollmentPublisher_EnrollmentConfirmedEvt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrollmentConfirmedEvt'
type EnrollmentPublisher_EnrollmentConfirmedEvt_Call struct {
	*mock.Call
}

// EnrollmentConfirmedEvt is a helper method to define mock.On call
//   - ctx context.Context
//   - enrollment fun.Enrollment
func (_e *EnrollmentPublisher_Expecter) EnrollmentConfirmedEvt(ctx interface{}, enrollment interface{}) *EnrollmentPublisher_EnrollmentConfirmedEvt_Call {
	return &EnrollmentPublisher_EnrollmentConfirmedEvt_Call{Call: _e.mock.On("EnrollmentConfirmedEvt", ctx, enrollment)}
}

func (_c *EnrollmentPublisher_EnrollmentConfirmedEvt_Call) Run(run func(ctx context.Context, enrollment fun.Enrollment)) *EnrollmentPublisher_EnrollmentConfirmedEvt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fun.Enrollment
		if args[1] != nil {
			arg1 = args[1].(fun.Enrollment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EnrollmentPublisher_EnrollmentConfirmedEvt_Call) Return(httpError common.HttpError) *EnrollmentPublisher_EnrollmentConfirmedEvt_Call {
	_c.Call.Return(httpError)
	return _c
}

func (_c *EnrollmentPublisher_EnrollmentConfirmedEvt_Call) RunAndReturn(run func(ctx context.Context, enrollment fun.Enrollment) common.HttpError) *EnrollmentPublisher_EnrollmentConfirmedEvt_Call {
	_c.Call.Return(run)
	return _c
}
