#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage make-deb <PACKAGE_NAME>"
    exit
fi

PACKAGE=$1

echo "Starting build: $PACKAGE"

DEB_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SRC_DIR="$DEB_DIR/.."
PKG_DIR="$DEB_DIR/$PACKAGE"
GO_MAIN="${SRC_DIR}/components/main/$PACKAGE.go"

echo -en "\033[1;32mSrc Dir: $SRC_DIR\nDeb Dir: $DEB_DIR \033[0m \n"

#Compile
if [ -f $GO_MAIN ]; then
    go build -o "$PKG_DIR/usr/sbin/$PACKAGE" "${GO_MAIN}"
    else
    echo -en "\033[1;33m Skipping Compile, Go Main Not Present:\n$GO_MAIN \033[0m \n";
fi

#Put Epoch Version
sed -i '' -e "s/__VERSION__/`date +%s`/g" $PKG_DIR/DEBIAN/control

#Build Deb
echo -en "\033[1;32m Building $PACKAGE.deb \033[0m \n"
dpkg-deb -Zgzip -b $PKG_DIR

#Git Reset
cd $PKG_DIR
git checkout -- .