pageInfo:
  title: Aman's Dashboard
  description: World at your fingertips.
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
sections:
  - name: Dashy
    icon: fas fa-rocket
    items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
      - title: Docs
        description: Refer Icons, Widgets, Keyboard Shortcuts, Pages
        provider: Dashy.to
        icon: far fa-book
        url: https://dashy.to/docs
      - title: Showcase
        description: See how others are using Dashy
        url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
        icon: far fa-grin-hearts
      - title: Config Guide
        description: See full list of configuration options
        url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
        icon: fas fa-wrench
      - title: Icons-Awesome
        description: Supported Icons
        url: https://fontawesome.com/search?q=git&o=r
        icon: fab fa-font-awesome
      - title: Icons-Material
        description: Supported Icons
        url: https://pictogrammers.com/library/mdi/
        icon: mdi-material-design
      - title: Support
        description: Get help with Dashy, raise a bug, or get in contact
        url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
        icon: far fa-hands-helping
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Entertainment
    icon: mdi-palette
    items:
      - title: Music
        description: Google Music
        icon: favicon
        url: https://music.youtube.com/watch?v=p4MYzp_kxwE&list=RDATdXiX
        hotkey: 1
        statusCheck: true
        tags: [music]
      - title: Pandora
        description: Pandora Playlist
        icon: favicon
        url: https://www.youtube.com/playlist?list=PL4FF2F5F7EF7ED26D
        tags: [music]
        hotkey: 2
    widgets:
      - type: clock
        options:
          timeZone: Asia/Kolkata
          format: en-GB
          hideDate: false
      - type: joke
        options:
          safeMode: false
          language: en
          category: Programming
      - type: iframe
        options:
          url: https://fiatleak.com/
  - name: MarketPlace
    icon: mdi-shopping
    items:
      - title: Quickr
        description: Quickr Sale
        icon: favicon
        url: https://www.quikr.com/MyQuikr?action=activeads
        tags: [sell]
      - title: Olx
        description: Olx Sale
        icon: favicon
        url: https://www.olx.in/nf/chat
        tags: [sell]
      - title: Amazon
        description: Amazon Buy
        icon: favicon
        url: https://www.amazon.in/hz/wishlist/genericItemsPage/3Q70DY9DUYY1Q?type=wishlist&filter=all&sort=default&viewType=list
        tags: [buy]
      - title: Flipkart
        description: Flipkart Buy
        icon: favicon
        url: https://www.flipkart.com/wishlist?link=home_wishlist
        tags: [buy]

    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
appConfig:
  theme: lissy
  layout: auto
  iconSize: medium
  language: en
  statusCheckInterval: 20
