apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the main cluster.
      multiCluster:
        clusterName: secondary
      network: secondary-network

      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: 10.102.135.18

    # The istio-ingressgateway is not required in the remote cluster if both clusters are on
    # the same network. To disable the istio-ingressgateway component, uncomment the lines below.

#  components:
#    ingressGateways:
#      - name: istio-ingressgateway
#        enabled: false
