restaurant:
  restaurantCount: 2 #No. of restaurants in Simulation
  kitchenCount: 2 #Parallel Orders each restaurant can handle
  #Assumption: All Dishes are made by all restaurants in same time
  dish:
    count: 10 #No. of Dishes offered by each restaurant
    cook: #All dishes will randomly fall between two times
      minTime: 4 #Cook time for fastest dish
      maxTime: 10 #Cook time for Slowest Dish

delivery:
  hires: 2 #No. of delivery boys available

sim:
  until: 40 #Time till which simulation should be run