restaurant:
  restaurantCount: 2 #No. of restaurants in Simulation
  kitchenCount: 2 #Parallel Orders each restaurant can handle
  #Assumption: All Dishes are made by all restaurants in same time
  dish:
    count: 10 #No. of Dishes offered by each restaurant
    cook: #All dishes will randomly fall between two times
      minTime: 4 #Cook time for fastest dish
      maxTime: 20 #Cook time for Slowest Dish

delivery:
  hires: 2 #No. of delivery boys available
  speed: 15 #Average Speed of Delivery Boy. Grid Squares Per Simulation Time Unit

sim:
  order:
    generateInterval: 4 #Generate new order about (randomized) every x time
  until: 200 #Time till which simulation should be run
  grid: #Simulation Grid Size all restaurants,delivery boys,customers will lie on this plane
    x: 1000
    y: 1000
  logLevel: CRITICAL #CRITICAL - Order Summary, INFO - Start/End each Order, DEBUG - Each Step in Order