---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  master.cnf: |
    [mysqld]
    server-id               = 1
    log_bin                 = /var/log/mysql/mysql-bin.log
  slave.cnf: |
    [mysqld]
    server-id               = 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: compute
            - name: MYSQL_USER
              value: aman
            - name: MYSQL_PASSWORD
              value: aman
          ports:
            - containerPort: 3306
          securityContext:
            runAsUser: 100
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/mysql.conf.d/master.cnf
              subPath: master.cnf
            - name: mysql-logs
              mountPath: /var/log/mysql
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: mysql-logs
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          securityContext:
            runAsUser: 100
          volumeMounts:
            - name: mysql-slave-config
              mountPath: /etc/mysql/mysql.conf.d/master.cnf
              subPath: slave.cnf
            - name: mysql-slave-logs
              mountPath: /var/log/mysql
      volumes:
        - name: mysql-slave-config
          configMap:
            name: mysql-config
        - name: mysql-slave-logs
          emptyDir: {}
