# https://doc.traefik.io/traefik/middlewares/http/overview/
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /mysqladmin
      - /app
      - /dashy

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefixregex
spec:
  stripPrefixRegex:
    regex:
      - "/[a-z0-9]+"
