apiVersion: v1
kind: Service
metadata:
  name: fun-app
  labels:
    app: fun-app
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }} #Service Port on which its exposed
    targetPort: 8080 #Connect to Container Port
  type: LoadBalancer
  selector:
    app: fun-app