// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/amanhigh/go-fun/models/common"

	mock "github.com/stretchr/testify/mock"

	tax "github.com/amanhigh/go-fun/models/tax"
)

// GainsRepository is an autogenerated mock type for the GainsRepository type
type GainsRepository struct {
	mock.Mock
}

type GainsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GainsRepository) EXPECT() *GainsRepository_Expecter {
	return &GainsRepository_Expecter{mock: &_m.Mock}
}

// GetAllRecords provides a mock function with given fields: ctx
func (_m *GainsRepository) GetAllRecords(ctx context.Context) ([]tax.Gains, common.HttpError) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRecords")
	}

	var r0 []tax.Gains
	var r1 common.HttpError
	if rf, ok := ret.Get(0).(func(context.Context) ([]tax.Gains, common.HttpError)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []tax.Gains); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tax.Gains)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) common.HttpError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}

	return r0, r1
}

// GainsRepository_GetAllRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRecords'
type GainsRepository_GetAllRecords_Call struct {
	*mock.Call
}

// GetAllRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GainsRepository_Expecter) GetAllRecords(ctx interface{}) *GainsRepository_GetAllRecords_Call {
	return &GainsRepository_GetAllRecords_Call{Call: _e.mock.On("GetAllRecords", ctx)}
}

func (_c *GainsRepository_GetAllRecords_Call) Run(run func(ctx context.Context)) *GainsRepository_GetAllRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GainsRepository_GetAllRecords_Call) Return(_a0 []tax.Gains, _a1 common.HttpError) *GainsRepository_GetAllRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GainsRepository_GetAllRecords_Call) RunAndReturn(run func(context.Context) ([]tax.Gains, common.HttpError)) *GainsRepository_GetAllRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordsForTicker provides a mock function with given fields: ctx, ticker
func (_m *GainsRepository) GetRecordsForTicker(ctx context.Context, ticker string) ([]tax.Gains, common.HttpError) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordsForTicker")
	}

	var r0 []tax.Gains
	var r1 common.HttpError
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]tax.Gains, common.HttpError)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []tax.Gains); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tax.Gains)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) common.HttpError); ok {
		r1 = rf(ctx, ticker)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}

	return r0, r1
}

// GainsRepository_GetRecordsForTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordsForTicker'
type GainsRepository_GetRecordsForTicker_Call struct {
	*mock.Call
}

// GetRecordsForTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *GainsRepository_Expecter) GetRecordsForTicker(ctx interface{}, ticker interface{}) *GainsRepository_GetRecordsForTicker_Call {
	return &GainsRepository_GetRecordsForTicker_Call{Call: _e.mock.On("GetRecordsForTicker", ctx, ticker)}
}

func (_c *GainsRepository_GetRecordsForTicker_Call) Run(run func(ctx context.Context, ticker string)) *GainsRepository_GetRecordsForTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GainsRepository_GetRecordsForTicker_Call) Return(_a0 []tax.Gains, _a1 common.HttpError) *GainsRepository_GetRecordsForTicker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GainsRepository_GetRecordsForTicker_Call) RunAndReturn(run func(context.Context, string) ([]tax.Gains, common.HttpError)) *GainsRepository_GetRecordsForTicker_Call {
	_c.Call.Return(run)
	return _c
}

// GetUniqueTickers provides a mock function with given fields: ctx
func (_m *GainsRepository) GetUniqueTickers(ctx context.Context) ([]string, common.HttpError) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueTickers")
	}

	var r0 []string
	var r1 common.HttpError
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, common.HttpError)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) common.HttpError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}

	return r0, r1
}

// GainsRepository_GetUniqueTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUniqueTickers'
type GainsRepository_GetUniqueTickers_Call struct {
	*mock.Call
}

// GetUniqueTickers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GainsRepository_Expecter) GetUniqueTickers(ctx interface{}) *GainsRepository_GetUniqueTickers_Call {
	return &GainsRepository_GetUniqueTickers_Call{Call: _e.mock.On("GetUniqueTickers", ctx)}
}

func (_c *GainsRepository_GetUniqueTickers_Call) Run(run func(ctx context.Context)) *GainsRepository_GetUniqueTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GainsRepository_GetUniqueTickers_Call) Return(_a0 []string, _a1 common.HttpError) *GainsRepository_GetUniqueTickers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GainsRepository_GetUniqueTickers_Call) RunAndReturn(run func(context.Context) ([]string, common.HttpError)) *GainsRepository_GetUniqueTickers_Call {
	_c.Call.Return(run)
	return _c
}

// NewGainsRepository creates a new instance of GainsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGainsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GainsRepository {
	mock := &GainsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
