image:
  repository: amanfdk/fun-app
  tag: latest

containerPort: 7080
svcPort: 9001
loadbalancerEnabled: true

#Readiness Probe
probe:
  enabled: true
  path: "/metrics"

vars:
  PORT: 7080
  DB_URL: "aman:aman@tcp(mysql-primary:3306)/compute?charset=utf8&parseTime=True&loc=Local"
  DB_LOG_LEVEL: "3" # 4 is Debug
  HTTP_REQUEST_TIMEOUT: "2s"

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefixregex@kubernetescrd
  path: /
  host: app.docker
