server:
  affinity: null

## Ingress configuration
##
ui:
  ingress:
    ## @param ingress.enabled Set to true to enable ingress record generation
    ##
    enabled: true
    hosts:
      - host: consul.docker
        paths:
          - /
    annotations: |
      'traefik.ingress.kubernetes.io/router.entrypoints': web
