image:
  repository: lissy93/dashy
  tag: latest

containerPort: 8080
svcPort: 4000

volumes:
  - name: dashy-data
    path: /app/user-data
    hostPath:
      path: /etc/files/dashy

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  path: /
  host: dashy.docker
