# https://github.com/elastic/helm-charts/blob/main/filebeat/values.yaml

daemonset:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"

      output.logstash:
        hosts: ["logstash:5044"]
        protocol: "http"

      logging.level: info
  # Ensure no secrets are mounted that aren't necessary
  secretMounts: []

# Disable deployment as we're using daemonset
deployment:
  enabled: false
