---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: load-balancer-example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-example
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load-balancer-example
  template:
    metadata:
      labels:
        app: load-balancer-example
    spec:
      containers:
        - image: gcr.io/google-samples/node-hello:1.0
          name: hello-world
          ports:
            - containerPort: 8080