# Authentication
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world

# Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secret
  annotations:
    kubernetes.io/service-account.name: hello-world
type: kubernetes.io/service-account-token

# ---- Authorization -----
# Role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: hello-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: hello-service-account
roleRef:
  kind: Role
  name: hello-role
  apiGroup: rbac.authorization.k8s.io

#Cluster Role
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: hello-cluster-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: hello-cluster-role
  apiGroup: rbac.authorization.k8s.io

# Service & Deployment Spec
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: load-balancer-example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-example
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load-balancer-example
  template:
    metadata:
      labels:
        app: load-balancer-example
    spec:
      containers:
        - image: gcr.io/google-samples/node-hello:1.0
          name: hello-world
          ports:
            - containerPort: 8080
          volumeMounts: #Token Refreshing every 10 Minutes
            - mountPath: /var/run/secrets/tokens
              name: hello-world-token
      volumes:
        - name: hello-world-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: hello-world
                  expirationSeconds: 600
                  path: hello-world-token