image:
  repository: docker.io/kennethreitz/httpbin
  tag: latest

containerPort: 80
svcPort: 8810

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefixregex@kubernetescrd
  path: /httpbin
