# https://artifacthub.io/packages/helm/jaegertracing/jaeger
nameOverride: "aman"

# https://www.jaegertracing.io/docs/1.29/getting-started/#all-in-one
# https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger#all-in-one-in-memory-configuration
provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - jaeger.docker
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false