# https://artifacthub.io/packages/helm/bitnami/kibana
## @section Kibana parameters
replicaCount: 1

## @section Elasticsearch parameters
elasticsearch:
  hosts: [elasticsearch]
  port: "9200"

ingress:
  enabled: true
  hostname: kibana.docker
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web