image:
  repository: osixia/openldap
  tag: latest

containerPort: 389
svcPort: 389

vars:
  LDAP_TLS: "false"
  LDAP_ADMIN_PASSWORD: "password"
  LDAP_ORGANISATION: "Example"
  LDAP_DOMAIN: "example.com"
  LDAP_BASE_DN: "dc=example,dc=com"
  LDAP_PORT: "389"
  LDAPS_PORT: "639"
