#  https://github.com/deliveryhero/helm-charts/blob/master/stable/locust/values.yaml

loadtest:
  name: locust-loadtest
  locust_locustfile: task.py
  locust_locustfile_configmap: locust-task
  locust_host: http://app:9001

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: locust.docker      
      path: /
      pathType: Prefix
  