# https://github.com/bitnami/charts/blob/main/bitnami/logstash/values.yaml
## @param configFileName Logstash configuration file name. It must match the name of the configuration file mounted as a configmap.
##
configFileName: logstash.conf
replicaCount: 1

# Push: curl -X POST -H "Content-Type: application/json" -d '{"message":"test log"}' http://docker:8080
# ES Verify: curl -X GET "http://docker:9200/logstash-*/_search?q=message:test%20log&pretty"
# Kibana: Discover > New Data View > Index log* to See Logs
input: |-
  http { 
    port => 8080 
  }
  beats {
    port => 5044
  }
  # Uncomment these if you need syslog input
  # udp {
  #   port => 1514
  #   type => syslog
  # }
  # tcp {
  #   port => 1514
  #   type => syslog
  # }


output: |-
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    manage_template => false
  }
  stdout { codec => rubydebug }

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
    - name: beats
      port: 5044

## @param filter Filter Plugins configuration
## ref: https://www.elastic.co/guide/en/logstash/current/filter-plugins.html
## e.g:
## filter: |-
##   grok {
##     match => { "message" => "%{COMBINEDAPACHELOG}" }
##   }
##   date {
##     match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
##   }
##
filter: ""
## @param output [string] Output Plugins configuration
## ref: https://www.elastic.co/guide/en/logstash/current/output-plugins.html
##