# https://artifacthub.io/packages/helm/pmint93/metabase
# https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker
image:
  repository: metabase/metabase
  tag: latest

containerPort: 3000
svcPort: 3000

volumes:
  - name: database
    path: /db
    hostPath:
      path: /tmp/mini/metabase

probe:
  enabled: true
  path: "/api/health"
  settings:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
    failureThreshold: 3

vars:
  MB_DB_FILE: "/db/h2.db"
  MB_DB_TYPE: "h2"
  MB_PASSWORD_COMPLEXITY: "weak"
  MB_PASSWORD_LENGTH: "4"
  # MB_DB_TYPE: "postgres"
  # MB_DB_DBNAME: "compute"
  # MB_DB_USER: "postgres"
  # MB_DB_PASS: "root"
  # MB_DB_HOST: "pg-primary"
  # MB_DB_PORT: "5432"

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  path: /
  host: metabase.docker