image:
  repository: rediscommander/redis-commander
  tag: latest

containerPort: 8081

vars:
  REDIS_HOSTS: "redis-master"

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  path: /
  host: redisadmin.docker
