#OneChart: https://github.com/gimlet-io/onechart/tree/master/charts/onechart/tests
image:
  repository: openresty/openresty
  tag: latest

containerPort: 80
svcPort: 8090

volumes:
  - name: default-conf
    path: /etc/nginx/conf.d/
    hostPath:
      path: /etc/files/resty/

#Readiness Probe
probe:
  enabled: true
  path: "/"
  settings:
    initialDelaySeconds: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 3
ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefixregex@kubernetescrd
  path: /
  host: resty.docker
  # host: docker
# replicas: 2
# podDisruptionBudgetEnabled: false

# command: sleep infinity

# vars:
#   REDIS_HOSTS: "redis-master"

#Debug/Troubleshoot Side Car: https://github.com/nicolaka/netshoot
#Lightweight: busybox (https://boxmatrix.info/wiki/BusyBox-Commands)
#sidecar:
#  repository: nicolaka/netshoot
#  tag: latest
#  shell: "/bin/bash"
#  command: "sleep infinity"
