#OneChart: https://github.com/gimlet-io/onechart/tree/master/charts/onechart/tests
image:
  repository: openresty/openresty
  tag: latest

containerPort: 80
svcPort: 8090

volumes:
  - name: default-conf
    path: /etc/nginx/conf.d/
    hostPath:
      path: /etc/files/resty/

#Readiness Probe
probe:
  enabled: true
  path: "/"
  settings:
    initialDelaySeconds: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 3
#TODO: Configure DNS Resolver and test https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/
ingress:
  host: resty.local

# replicas: 2
# podDisruptionBudgetEnabled: false

# command: sleep infinity

#Debug Side Car: https://github.com/digitalocean/doks-debug
sidecar:
  repository: digitalocean/doks-debug
  tag: latest
  shell: "/bin/bash"
  command: "sleep infinity"
