#OneChart: https://github.com/gimlet-io/onechart/tree/master/charts/onechart/tests
# Values: https://github.com/gimlet-io/onechart/blob/master/charts/onechart/values.yaml
image:
  repository: openresty/openresty
  tag: latest

containerPort: 80
svcPort: 8090

volumes:
  - name: default-conf
    path: /etc/nginx/conf.d/
    hostPath:
      path: /etc/files/resty/

#Readiness Probe
probe:
  enabled: true
  path: "/"
  settings:
    initialDelaySeconds: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 3
ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefixregex@kubernetescrd
  path: /
  host: resty.docker
  # host: docker
# replicas: 2
# podDisruptionBudgetEnabled: false
# podAnnotations:
  # co.elastic.logs/enabled: "true"
podLabels:
  vector.dev/include: "true"

resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"

securityContext:
  runAsUser: 100

# command: sleep infinity

# vars:
#   REDIS_HOSTS: "redis-master"

# Create Secrets manually and mount as ENV Variables
# kubectl create secret generic my-secret --from-env-file=/home/aman/.env
# existingSecrets:
  # - name: my-secret
    # optional: false

## Debug/Troubleshoot ##
# Side Car: https://github.com/nicolaka/netshoot
# Lightweight: busybox (https://boxmatrix.info/wiki/BusyBox-Commands)
#sidecar:
#  repository: nicolaka/netshoot
#  tag: latest
#  shell: "/bin/bash"
#  command: "sleep infinity"

# Shared Debug Directory between Main and Sidecar Containers
# volumes:
#   - name: preet
#     path: /aman
#     size: 1Gi
# Persistent Value
# - name: webui
#   path: /app/backend/data
#   size: 1Gi
#   storageClass: standard

## Service Type (Default NodePort)
# nodePortEnabled: false (Makes Cluster IP)
# loadbalancerEnabled: true (Makes Load Balancer)