# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# Configure Traefik static configuration

# Configure ports
ports:
  # The name of this one can't be changed as it is used for the readiness and
  # liveness probes, but you can adjust its config to your liking
  traefik:
    port: 9000
    exposedPort: 9000
    protocol: TCP

## Create HorizontalPodAutoscaler object.
##
autoscaling:
  enabled: false
#   minReplicas: 1
#   maxReplicas: 10

additionalArguments:
  - "--entrypoints.websecure.http.tls.certresolver=default"
  - "--entrypoints.websecure.http.tls.domains[0].main=*.docker"
  - "--certificatesresolvers.default.selfsigned=true"

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data