# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# Configure Traefik static configuration

# Configure ports
ports:
  # The name of this one can't be changed as it is used for the readiness and
  # liveness probes, but you can adjust its config to your liking
  traefik:
    port: 9000
    exposedPort: 9000
    protocol: TCP

# TASK: Fix Cert Mounting
volumes:
  - name: certs
    hostPath:
      path: /etc/files/certs
      type: Directory
    mountPath: /etc/certs
    readOnly: true

## Create HorizontalPodAutoscaler object.
##
autoscaling:
  enabled: false
#   minReplicas: 1
#   maxReplicas: 10