image:
  repository: ghcr.io/open-webui/open-webui
  tag: main

containerPort: 8080 
svcPort: 3000

volumes:
  - name: webui
    path: /app/backend/data
    size: 1Gi
    storageClass: standard

vars:
  OLLAMA_BASE_URL: "http://host.minikube.internal:11434"
  WEBUI_AUTH: "false"
  OPENAI_API_BASE_URLS: "https://api.together.xyz/v1;https://openrouter.ai/api/v1;"
  # XXX: only one Key Working (Last)
  OPENAI_API_KEYS: "${TOGETHERAI_API_KEY};${OPENROUTER_API_KEY};"

resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "2000m"
    memory: "2000Mi"

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  path: /
  host: webui.docker

existingSecrets:
  - name: secret-keys
    optional: true
