// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/amanhigh/go-fun/models/common"
	"github.com/amanhigh/go-fun/models/tax"
	mock "github.com/stretchr/testify/mock"
)

// NewGainsComputationManager creates a new instance of GainsComputationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGainsComputationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *GainsComputationManager {
	mock := &GainsComputationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GainsComputationManager is an autogenerated mock type for the GainsComputationManager type
type GainsComputationManager struct {
	mock.Mock
}

type GainsComputationManager_Expecter struct {
	mock *mock.Mock
}

func (_m *GainsComputationManager) EXPECT() *GainsComputationManager_Expecter {
	return &GainsComputationManager_Expecter{mock: &_m.Mock}
}

// ComputeGainsFromTrades provides a mock function for the type GainsComputationManager
func (_mock *GainsComputationManager) ComputeGainsFromTrades(ctx context.Context, trades []tax.Trade) ([]tax.Gains, common.HttpError) {
	ret := _mock.Called(ctx, trades)

	if len(ret) == 0 {
		panic("no return value specified for ComputeGainsFromTrades")
	}

	var r0 []tax.Gains
	var r1 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []tax.Trade) ([]tax.Gains, common.HttpError)); ok {
		return returnFunc(ctx, trades)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []tax.Trade) []tax.Gains); ok {
		r0 = returnFunc(ctx, trades)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tax.Gains)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []tax.Trade) common.HttpError); ok {
		r1 = returnFunc(ctx, trades)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}
	return r0, r1
}

// GainsComputationManager_ComputeGainsFromTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeGainsFromTrades'
type GainsComputationManager_ComputeGainsFromTrades_Call struct {
	*mock.Call
}

// ComputeGainsFromTrades is a helper method to define mock.On call
//   - ctx context.Context
//   - trades []tax.Trade
func (_e *GainsComputationManager_Expecter) ComputeGainsFromTrades(ctx interface{}, trades interface{}) *GainsComputationManager_ComputeGainsFromTrades_Call {
	return &GainsComputationManager_ComputeGainsFromTrades_Call{Call: _e.mock.On("ComputeGainsFromTrades", ctx, trades)}
}

func (_c *GainsComputationManager_ComputeGainsFromTrades_Call) Run(run func(ctx context.Context, trades []tax.Trade)) *GainsComputationManager_ComputeGainsFromTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []tax.Trade
		if args[1] != nil {
			arg1 = args[1].([]tax.Trade)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GainsComputationManager_ComputeGainsFromTrades_Call) Return(gainss []tax.Gains, httpError common.HttpError) *GainsComputationManager_ComputeGainsFromTrades_Call {
	_c.Call.Return(gainss, httpError)
	return _c
}

func (_c *GainsComputationManager_ComputeGainsFromTrades_Call) RunAndReturn(run func(ctx context.Context, trades []tax.Trade) ([]tax.Gains, common.HttpError)) *GainsComputationManager_ComputeGainsFromTrades_Call {
	_c.Call.Return(run)
	return _c
}
