// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/amanhigh/go-fun/models/barkat"
	"github.com/amanhigh/go-fun/models/common"
	mock "github.com/stretchr/testify/mock"
)

// NewTagManager creates a new instance of TagManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagManager {
	mock := &TagManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TagManager is an autogenerated mock type for the TagManager type
type TagManager struct {
	mock.Mock
}

type TagManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TagManager) EXPECT() *TagManager_Expecter {
	return &TagManager_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function for the type TagManager
func (_mock *TagManager) CreateTag(ctx context.Context, journalID string, tag barkat.Tag) (*barkat.Tag, common.HttpError) {
	ret := _mock.Called(ctx, journalID, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 *barkat.Tag
	var r1 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, barkat.Tag) (*barkat.Tag, common.HttpError)); ok {
		return returnFunc(ctx, journalID, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, barkat.Tag) *barkat.Tag); ok {
		r0 = returnFunc(ctx, journalID, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*barkat.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, barkat.Tag) common.HttpError); ok {
		r1 = returnFunc(ctx, journalID, tag)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}
	return r0, r1
}

// TagManager_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type TagManager_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID string
//   - tag barkat.Tag
func (_e *TagManager_Expecter) CreateTag(ctx interface{}, journalID interface{}, tag interface{}) *TagManager_CreateTag_Call {
	return &TagManager_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, journalID, tag)}
}

func (_c *TagManager_CreateTag_Call) Run(run func(ctx context.Context, journalID string, tag barkat.Tag)) *TagManager_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 barkat.Tag
		if args[2] != nil {
			arg2 = args[2].(barkat.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TagManager_CreateTag_Call) Return(tag1 *barkat.Tag, httpError common.HttpError) *TagManager_CreateTag_Call {
	_c.Call.Return(tag1, httpError)
	return _c
}

func (_c *TagManager_CreateTag_Call) RunAndReturn(run func(ctx context.Context, journalID string, tag barkat.Tag) (*barkat.Tag, common.HttpError)) *TagManager_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type TagManager
func (_mock *TagManager) DeleteTag(ctx context.Context, journalID string, tagID string) common.HttpError {
	ret := _mock.Called(ctx, journalID, tagID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) common.HttpError); ok {
		r0 = returnFunc(ctx, journalID, tagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.HttpError)
		}
	}
	return r0
}

// TagManager_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type TagManager_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID string
//   - tagID string
func (_e *TagManager_Expecter) DeleteTag(ctx interface{}, journalID interface{}, tagID interface{}) *TagManager_DeleteTag_Call {
	return &TagManager_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, journalID, tagID)}
}

func (_c *TagManager_DeleteTag_Call) Run(run func(ctx context.Context, journalID string, tagID string)) *TagManager_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TagManager_DeleteTag_Call) Return(httpError common.HttpError) *TagManager_DeleteTag_Call {
	_c.Call.Return(httpError)
	return _c
}

func (_c *TagManager_DeleteTag_Call) RunAndReturn(run func(ctx context.Context, journalID string, tagID string) common.HttpError) *TagManager_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type TagManager
func (_mock *TagManager) ListTags(ctx context.Context, journalID string, tagType string) ([]barkat.Tag, common.HttpError) {
	ret := _mock.Called(ctx, journalID, tagType)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []barkat.Tag
	var r1 common.HttpError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]barkat.Tag, common.HttpError)); ok {
		return returnFunc(ctx, journalID, tagType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []barkat.Tag); ok {
		r0 = returnFunc(ctx, journalID, tagType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]barkat.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) common.HttpError); ok {
		r1 = returnFunc(ctx, journalID, tagType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.HttpError)
		}
	}
	return r0, r1
}

// TagManager_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type TagManager_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID string
//   - tagType string
func (_e *TagManager_Expecter) ListTags(ctx interface{}, journalID interface{}, tagType interface{}) *TagManager_ListTags_Call {
	return &TagManager_ListTags_Call{Call: _e.mock.On("ListTags", ctx, journalID, tagType)}
}

func (_c *TagManager_ListTags_Call) Run(run func(ctx context.Context, journalID string, tagType string)) *TagManager_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TagManager_ListTags_Call) Return(tags []barkat.Tag, httpError common.HttpError) *TagManager_ListTags_Call {
	_c.Call.Return(tags, httpError)
	return _c
}

func (_c *TagManager_ListTags_Call) RunAndReturn(run func(ctx context.Context, journalID string, tagType string) ([]barkat.Tag, common.HttpError)) *TagManager_ListTags_Call {
	_c.Call.Return(run)
	return _c
}
