server:
  port: 8080

db:
  auto_migrate: true
  migration_source: /Users/amanpreet.singh/IdeaProjects/Go/go-fun/learn/frameworks/orm/db/go-migrate/migration
  url: aman:aman@tcp(docker:3306)/compute?charset=utf8&parseTime=True&loc=Local

http:
  dial_timeout: 200ms
  request_timeout: 2s
  idle_connection_timeout: 30s

  keep_alive: true
  compression: false
  idle_connections_per_host: 20