version: '3'
# Run Generic App Under Development along with DB's etc
services:
  fun:
    # http://localhost:9090/metrics
    image: amanfdk/fun-app
    restart: always
    ports:
      - 9090:7890
    environment:
      PORT: 7890
      DB_URL: "aman:aman@tcp(mysql:3306)/compute?charset=utf8&parseTime=True&loc=Local"
      DB_LOG_LEVEL: "4"
      HTTP_REQUEST_TIMEOUT: "2s"





