version: '3'

services:
  #dpkg-deb -b <DEBIAN DIR PATH>
  #Build: dman run build-box 1 'cd /var/Projects/Go/go-fun/apps/components/main/; go build -o app fun-app.go'
   build-box:
     build: ../build-box
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/
     environment:
       GOPATH: /var/Projects/GoArena

  #dpkg -i <DEB_FILE>
   target:
     image: openjdk:11.0-stretch
     command: sleep 100000
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/