version: '3'

services:
   jenkins:
     image: jenkins/jenkins:lts
     restart: always
     volumes:
       - jenkins_home:/var/jenkins_home
       - $CODE_PATH:/var/projects/
     ports:
      - 8080:8080
      - 50000:50000

  #dpkg-deb -b <DEBIAN DIR PATH>
   build-box:
     build: ../build-box
     volumes:
       - /Users/amanpreet.singh/IdeaProjects/GoArena/:/var/GoArena/
     environment:
       GOPATH: /var/GoArena

  #dpkg -i <DEB_FILE>
   target:
     image: debian:7
     command: sleep 100000
     volumes:
       - /Users/amanpreet.singh/IdeaProjects/GoArena/:/var/GoArena/

volumes:
  jenkins_home: