version: '3'

services:
   jenkins:
     image: jenkins/jenkins:lts
     restart: always
     volumes:
       - jenkins_home:/var/jenkins_home
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/
     ports:
      - 8100:8080
      - 50000:50000

  #dpkg-deb -b <DEBIAN DIR PATH>
   build-box:
     build: ../build-box
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/
     environment:
       GOPATH: /var/Go

  #dpkg -i <DEB_FILE>
   target:
     image: debian:9
     command: sleep 100000
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/

volumes:
  jenkins_home: