version: '3'

services:
   jenkins:
     image: jenkins/jenkins:lts
     restart: always
     volumes:
       - jenkins_home:/var/jenkins_home
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/
     ports:
      - 8100:8080
      - 50000:50000

  #dpkg-deb -b <DEBIAN DIR PATH>
  #Build: dman run build-box 1 'cd /var/Projects/Go/go-fun/apps/components/main/; go build -o app fun-app.go'
   build-box:
     build: ../build-box
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/
     environment:
       GOPATH: /var/Projects/GoArena

  #dpkg -i <DEB_FILE>
   target:
     image: openjdk:11.0-stretch
     command: sleep 100000
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/

volumes:
  jenkins_home: