version: '3'

services:
  #dpkg-deb -b <DEBIAN DIR PATH>
  #dpkg -i <DEB_FILE>
  #Build: dman run build 1 'cd /var/Projects/Go/go-fun/apps/components/main/; go build -o app fun-app.go'
   build:
     build: ../builds/build-box
     volumes:
       - /Users/amanpreet.singh/IdeaProjects:/var/Projects/

     ports:
     - 9600:9600
     - 9605:9605
     - 9610:9610
     environment:
       GOPATH: /var/Projects/GoArena