version: '3.0'
services:
  consul1:
    image: consul:latest
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500" #UI Port
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0"
  consul2:
    image: consul:latest
    hostname: "consul2"
    command: "agent -server -join consul1 -disable-host-node-id"
    depends_on:
      - consul1
  consul3:
    image: consul:latest
    hostname: "consul3"
    command: "agent -server -join consul1 -disable-host-node-id"
    depends_on:
      - consul1