version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

configs:
  elastic_config:
    file: ./files/elasticsearch.yml
#  logstash_config:
#    file: ./logstash/config/logstash.yml
#  logstash_pipeline:
#    file: ./logstash/pipeline/logstash.conf
#  kibana_config:
#    file: ./kibana/config/kibana.yml