version: "3"

# https://hbase.apache.org/book.html#quickstart
# login to hbase and run "hbase shell"
# create 'test', 'cf'
# list 'test';describe 'test'
# put 'test', 'row1', 'cf:a', 'value1'; put 'test', 'row2', 'cf:b', 'value2'
# get 'test', 'row1; scan 'test'

# disable 'test'; drop 'test'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./files/hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "compose_namenode_1:50070"
    env_file:
      - ./files/hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    environment:
      SERVICE_PRECONDITION: "compose_namenode_1:50070 compose_datanode_1:50075"
    env_file:
      - ./files/hadoop.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    environment:
      SERVICE_PRECONDITION: "compose_namenode_1:50070 compose_datanode_1:50075 compose_resourcemanager_1:8088"
    env_file:
      - ./files/hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "compose_namenode_1:50070 compose_datanode_1:50075 compose_resourcemanager_1:8088"
    env_file:
      - ./files/hadoop.env

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "compose_namenode_1:50070 compose_datanode_1:50075"
    env_file:
      - ./files/hbase-standalone.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
