#ldapsearch -H ldap://docker:389 -xLL -D 'cn=admin,dc=example,dc=com' -b 'dc=example,dc=com' -W '(cn=admin)'
#Admin Login: Username:cn=admin,dc=example,dc=com Password: password

version: '3'
services:
  ldap:
    image: osixia/openldap
    environment:
      LDAP_TLS: 'false'
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_ORGANISATION: "Example"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: "dc=example,dc=com"
    ports:
      - "389:389"
      - "639:639"
  ldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS=false:
    ports:
      - "8080:80"
    depends_on:
      - ldap