# * rs.initiate({
#  _id: "shard1",
#  version: 1,
#  members: [
#  { _id: 0, host: "mongo1:27017" },
#  { _id: 1, host: "mongo2:27017" },
#  { _id: 2, host: "mongo3:27017" }
#  ]
#   })
# * rs.status()
# * Create Admin:
#   - use admin
#   - db.createUser(
#  {
#    user: "admin",
#    pwd: "changeme",
#    roles: [ { role: "root", db: "admin" } ]
#   }
#  );
# * Add Member (only on primary as admin) -  rs.add( { host: "mongo1:27017"} )
# * Remove Member (only on primary as admin) -  rs.remove("mongo1:27017")
#

version: '3.0'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root