# Docker Login - mongo -u root -p root --host compose_mongo_1 admin
# Seed Script - dman run mongo 1 "mongo -u root -p root < /scripts/mongo.js"

version: '3.0'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./files/scripts/:/scripts
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

#  nosql:
#    image: mongoclient/mongoclient
#    restart: always
#    ports:
#      - 3000:3000
#    environment:
#      MONGO_URL: "mongodb://root:root@mongo:27017/admin"