version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compute
      MYSQL_USER: aman
      MYSQL_PASSWORD: aman

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8888
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_PLUGINS: sql-log

#  myadmin:
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - 8888:9999
#    environment:
#      PMA_HOST: mysql

volumes:
  mysql_data: