version: '3'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - 'mysql_master_data:/bitnami/mysql/data'
    environment:
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
      MYSQL_USER: aman
      MYSQL_PASSWORD: aman
      MYSQL_DATABASE: compute
      #ALLOW_EMPTY_PASSWORD is recommended only for development.
      #ALLOW_EMPTY_PASSWORD=yes
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  slave:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - 3307:3306
    depends_on:
      - mysql
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
      MYSQL_USER: aman
      MYSQL_PASSWORD: aman
      MYSQL_DATABASE: compute
      MYSQL_MASTER_HOST: mysql
      MYSQL_MASTER_PORT_NUMBER: 3306
      MYSQL_MASTER_ROOT_PASSWORD: root
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_PLUGINS: sql-log

#  myadmin:
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - 9999:8888
#    environment:
#      PMA_HOST: mysql

volumes:
  mysql_master_data: