version: '3'
services:
  opa:
    image: openpolicyagent/opa:0.11.0
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
  api_server:
    image: openpolicyagent/demo-restful-api:0.2
    ports:
      - 5000:5000
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/httpapi/authz
