version: '3'

services:
  tinyproxy:
    image: travix/tinyproxy:latest
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./files/tinyproxy.conf:/etc/tinyproxy.conf
      - ./files/whitelist.conf:/etc/whitelist.conf

  squid:
    image: sameersbn/squid:latest
    restart: always
    ports:
      - 3128:3128
    volumes:
      - ./files/squid-config.conf:/etc/squid/squid.conf
      - ./files/whitelist.conf:/etc/whitelist.conf

  nginx:
    image: nginx
    restart: always
    ports:
      - 81:81
      - 82:82
      - 83:83
      - 84:84
      - 85:85
    volumes:
      - ./files/whitelist.conf:/etc/whitelist.conf
      - ./files/nginx.conf:/etc/nginx/conf.d/default.conf

  resty:
    image: openresty/openresty:alpine
    restart: always
    ports:
      - 90:80
    volumes:
      - ./files/whitelist.conf:/etc/whitelist.conf
      - ./files/resty.conf:/etc/nginx/conf.d/default.conf