# Increment: dman run rn5 1 'redis-cli -c incr mycounter'
# Write: redis-cli -c set mypasswd lol
# Read: redis-cli -c get mypasswd

version: '3'
services:
  rn0:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=rn0 rn1 rn2 rn3 rn4 rn5'

  rn1:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=rn0 rn1 rn2 rn3 rn4 rn5'

  rn2:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=rn0 rn1 rn2 rn3 rn4 rn5'

  rn3:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=rn0 rn1 rn2 rn3 rn4 rn5'

  rn4:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=rn0 rn1 rn2 rn3 rn4 rn5'

  rn5:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - rn0
      - rn1
      - rn2
      - rn3
      - rn4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
# Minimum 3 Nodes required for Cluster, 6 With 1 Replica for each Node
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=rn0 rn1 rn2 rn3 rn4 rn5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS="rn0"
    ports:
      - 8081:8081

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local