version: '3'

# Requires postgres image to be up.
# Default Sonar Login: admin/admin
services:
  sonarqube:
    image: sonarqube
    ports:
      - '9000:9000'
    environment:
      SONARQUBE_JDBC_USERNAME: aman
      SONARQUBE_JDBC_PASSWORD: aman
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/compute
    command: -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m