# Check Docker Logs for Root Key & Seal Key
# vault kv put secret/aman aman="preet"
# vault kv get secret/aman or http://127.0.0.1:8200/ui/vault/secrets/secret/list

# vault.json change for consul backend
# "consul": {
#   "address": "consul1:8500",
#   "advertise_addr":"http://vault:8200",
#   "path": "/vault/"
# }

# Vault Mysql Management
# vault secrets enable database
# vault write database/config/aman-mysql plugin_name=mysql-database-plugin connection_url="root:root@tcp(compose_mysql_1:3306)/" allowed_roles="aman-mysql-role" username="root" password="root"
# vault write database/roles/aman-mysql-role db_name=aman-mysql creation_statements="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON *.* TO '{{name}}'@'%';"     default_ttl="1h"     max_ttl="24h"
# vault read database/creds/aman-mysql-role

# Vault Mongo Management
#vault secrets enable database
#vault write database/config/aman-mongo plugin_name=mongodb-database-plugin allowed_roles="aman-mongo-role" connection_url="mongodb://{{username}}:{{password}}@compose_mongo_1:27017/admin" username="root" password="root"
#vault write database/roles/aman-mongo-role db_name=aman-mongo creation_statements='{ "db": "admin", "roles": [{ "role": "readWrite" }, {"role": "read", "db": "compute"}] }' default_ttl="1h" max_ttl="24h"
#vault read database/creds/aman-mongo-role

version: '3.0'
services:
  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
    volumes:
      - ./files/vault.json:/vault/config/vault.json:rw
    cap_add:
      - IPC_LOCK