# Check Docker Logs for Root Key & Seal Key

# vault.json change for consul backend
# "consul": {
#   "address": "consul1:8500",
#   "advertise_addr":"http://vault:8200",
#   "path": "/vault/"
# }

#dman run vault 1 "./scripts/vault.sh" -l sh

version: '3.0'
services:
  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_TOKEN: "root-token"
    volumes:
      - ./files/vault.json:/vault/config/vault.json:rw
      - ./files/scripts/:/scripts
    cap_add:
      - IPC_LOCK