root = "."
tmp_dir = "/tmp"

[build]
  cmd = "just build"
  full_bin = "${KOHAN_BINARY}"
  delay = 1000
  include_ext = ["go", "templ"]
  exclude_regex = ["_test\\.go", "_templ\\.go", "testdata/.*"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
