root = "../.."
tmp_dir = "/tmp"

[build]
  cmd = "just components/fun-app/build"
  full_bin = "${FUN_APP_BINARY}"
  delay = 1000
  include_ext = ["*"]
  exclude_dir = ["bin", ".git", "tmp", ".tmp", "temp", ".cache", "vendor", "node_modules", "dist", "build", "coverage", "target"]
  exclude_regex = ["_test\\.go", "_templ\\.go", "testdata/.*"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
