# List Jobs: act -l
# Run Job: act -q

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: INSTALL -> Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: INSTALL -> Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: SETUP -> Dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          make setup-tools

      - name: SETUP -> Build
        run: |
          make all

      - name: COVERAGE -> Report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverprofile.out,./components/operator/cover.out,./components/fun-app/it/cover/profile
          flags: unittests
          verbose: true
          name: codecov-go-fun