# List Jobs: act -l
# Run Job: act -q

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CODE -> Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GO -> Setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: GO -> Dependencies
        working-directory: ./common
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: HELM -> Install
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: HELM -> Repo Setup
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: GO -> Releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v1.0.2

      - name: COVERAGE -> Report
        uses: codecov/codecov-action@v3
        # FIXME: Second Coverage File not Working
        with:
          files: ./coverprofile.out,./components/fun-app/it/cover/profile
          flags: unittests
          verbose: true
          name: codecov-go-fun