name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install deps
        working-directory: ./common
        run: |
          export GOPATH=~/go
          export PATH=$PATH:$GOPATH/bin
          go env         
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Go Releaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --skip-publish --clean
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverprofile.out
          flags: unittests
          verbose: true
          name: codecov-go-fun
