name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install deps
        working-directory: ./common
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Go Releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v1.0.2

      - name: Debug Step
        run: |
          test -f /tmp/gocover/profile && echo "File exists" || echo "File does not exist";
          ls /tmp;
          ls /tmp/gocover;
          
      - name: Report Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverprofile.out,/tmp/gocover/profile
          flags: unittests
          verbose: true
          name: codecov-go-fun