name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install deps
      run: |
#        TODO: Move to Ginkgo GA
        go get github.com/onsi/ginkgo/v2@v2.0.0-rc2
        go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.0.0-rc2
        go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.0.0-rc2
        go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.0.0-rc2
        go install github.com/onsi/ginkgo/v2/ginkgo


    - name: Go Releaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
