# Job: https://github.com/amanhigh/go-fun/actions/workflows/release.yml
# Release: https://github.com/amanhigh/go-fun/tags
name: Chart Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: INSTALL -> X11 Libs
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libx11-dev \
            libxcb1-dev \
            libxau-dev \
            libxdmcp-dev
      
      - name: INSTALL -> Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: SETUP -> Onetime
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          make setup-tools
        
      - name: SETUP -> Package
        run: |
          make helm-package

      - name: SETUP -> Publish
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: components/fun-app
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
